Our Receive Address
EdgeApp/edge-currency-plugins pull request #102
Opened 2021-03-30 03:26 UTC by passabilities

2021-03-30 03:46 UTC, passabilities commented on src/common/utxobased/db/Models/ProcessorTransaction.ts
> +  const { tx, processor, walletTools } = args
emit event when transaction is updated via the internal function in processor.

2021-03-30 04:40 UTC, thehobbit85 requested changes
Address Comment

2021-04-03 04:19 UTC, thehobbit85 approved these changes

2021-04-10 07:59 UTC, thehobbit85 approved these changes

2021-04-10 07:59 UTC, merged