Pick Next Task
EdgeApp/edge-currency-plugins pull request #103
Opened 2021-03-31 17:53 UTC by TheCharlatan

Based on #98 and #96 

This is an attempt of a port of the pickNextTask routine from the old edge-currency-bitcoin plugin. An attempt is made to use promises where possible and execute all networking routines through pickNextTask.

PickNextTask allows the networking and database operations especially during synching, but also during normal operation, to run completely async.

PickNextTask is triggered when the socket's pending message queue is empty enough. It may also be triggered periodically by the timeout in the main sockets queue.

To keep track of jobs to be done, a cache object is used that is passed from call to call.

The promises's catch is used to enable full recovery upon a task failure, meaning allowing the task to be run again in case of a database or network error.

A wrapper class around the promise, called Deferred, is introduced to facilitate resolve calls on the promise outside of the Promise constructor's body. Deferred is additionally templated to give some type assurances on return.

2021-04-05 16:19 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +  const taskCache: TaskCache = {
Use Memlet here to get fixed memory size. Use the same top-level disklet.

2021-04-05 16:19 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +    console.log(percent)
Remove.

2021-04-05 16:22 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +          address,
Revert this to script pubkey.

2021-04-05 16:26 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +  updateTransactionsCache: Map<string, UpdateTransactionsCacheState>
Just use a boolean here.

2021-04-05 16:29 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +        address,
Change to scriptPubkey

2021-04-05 16:31 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +  console.log({
Change to io

2021-04-05 16:38 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +        address
Check if this really is address.

2021-04-05 16:43 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +  const addressesToWatch: Map<string, ShortPath> = new Map<string, ShortPath>()
Use Memlet here as well, review if we really need two caches.

2021-04-05 16:50 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +        const path = addressesToWatch.get(response.address)
Check if addresses have a path when adding to addressesToWatch/addressSubscribe

2021-04-05 16:56 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +            throw new Error('failed to add to transaction cache')
Make sure you want to kill the wallet here.

2021-04-05 16:58 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +  // Check if there are any addresses pending to be subscribed
Subscribe to none-used addresses first, then fetch the transactions, then to used addresses.

2021-04-05 17:03 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +  for (const [utxo, state] of rawUtxosCache) {
Move towards the top, try to get the user to be able to spend money asap, then fetch address, then tx history.

2021-04-05 17:03 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +  for (const [address, state] of processedUtxosCache) {
Move towards the top, try to get the user to be able to spend money asap, then fetch address, then tx history.

2021-04-05 17:05 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +  address: string
Check if it is address or scriptPubkey.

2021-04-05 17:08 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +const processFormatAddresses = async (
Turn this into generic function that receives args and executor, then use that every time we need to loop over all branches for a format.

2021-04-05 17:09 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +  for (const format of formatsToProcess) {
Replace with format branch from below.

2021-04-05 17:11 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +    console.log('processing path', path)
Remove console.log

2021-04-05 17:11 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +    let scriptPubkey = await processor.fetchScriptPubkeyByPath(path)
Just pick new param.

2021-04-05 17:17 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
>    const addressData = await processor.fetchAddressByScriptPubkey(scriptPubkey)
Check if the address is null here, throw!

2021-04-05 17:18 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +      if (used && !(addressData?.used ?? false) && page === 1) {
Use the null check further above, so need to check again.

2021-04-05 17:31 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +        currentUtxoIds.delete(utxo.id)
Turn console.log into io log on line 964

2021-04-05 17:40 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +        const deferred = new Deferred<ITransaction>()
Do it everywhere: Rename deferred to transactionTask or something more descriptive.

2021-04-05 17:48 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +        args.onAddressChecked()
Call this when the addresses has run through all cache tasks, e.g. when it is no longer in the cache.

2021-04-05 17:55 UTC, TheCharlatan commented on src/common/utxobased/network/BlockBook.ts
> +  ): Promise<any> {
Try typing this again once it is merged to master.

2021-04-05 19:05 UTC, TheCharlatan commented on src/common/utxobased/network/BlockBookAPI.ts
> +  params: unknown
Add cleaner and use it on return task

2021-04-05 19:19 UTC, TheCharlatan commented on src/common/utxobased/network/BlockBookAPI.ts
> +  params: unknown
Also add error message to use when cleaner failed or rejected.

2021-04-05 19:21 UTC, TheCharlatan commented on src/common/utxobased/network/Socket.ts
> -  setupTimer()
Re-add

2021-04-05 19:23 UTC, TheCharlatan commented on src/common/utxobased/network/Socket.ts
> +    setupTimer()
Remove and re-add in onMessage.

2021-04-05 19:24 UTC, TheCharlatan reviewed
Address comments.

2021-04-05 19:26 UTC, thehobbit85 requested changes
Address Comments.
First commit - resolve conflicts
Second commit - fixes
Third commit - changing names of params

2021-04-06 21:39 UTC, closed without merging

2021-04-08 08:23 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +  updateTransactionsCache: Map<string, UpdateTransactionsCacheState>
Actually this needs to be an object to preserve changing it by reference.

2021-04-08 09:21 UTC, TheCharlatan commented on src/common/utxobased/network/BlockBook.ts
> +    await promisifyWsMessage(broadcastTxMessage(transaction))
Doesn't seem worth the added type complexity to me.

2021-04-08 09:22 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +  const addressesToWatch: Map<string, ShortPath> = new Map<string, ShortPath>()
Defer this to a later PR.

2021-04-08 09:27 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +const processFormatAddresses = async (
This is changed again after rebase, so I don't think it's worth touching it again before rebase.

2021-04-08 09:28 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +  for (const format of formatsToProcess) {
Same as format branch above, this is changed after rebasing on current master, so has to be fixed independently upon rebase.

2021-04-08 10:29 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +  // Check if there are any addresses pending to be subscribed
This requires some change in setLookAhead by the looks of it to distinguish between used and non-used transactions. Subscribe is anyway only on an array, so not sure what benefit this brings.

2021-04-08 10:31 UTC, TheCharlatan commented on src/common/utxobased/network/BlockBookAPI.ts
> +  params: unknown
Can this be done in a later task? Seems to only be tangentially related to pick next task. The current code also has no cleaners.

2021-04-08 11:27 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +        const path = addressesToWatch.get(response.address)
This seems to already be the case in both instances setting the addressSubscribeCache.  SetLookAhead uses walletTools to get the address by path, processPathAddresses, gets the addresses from getNumAddressesFromPathPartition.