Sam/bsv patches
EdgeApp/edge-currency-plugins pull request #314
Opened 2022-06-07 01:34 UTC by samholmes

2022-06-07 04:09 UTC, paullinator requested changes

2022-06-07 04:09 UTC, paullinator commented on src/common/utxobased/info/bitcoinsv.ts
> +    blockbookServers: ['ws://localhost:8008'],
Why is this local host?

2022-06-08 09:41 UTC, thehobbit85 approved these changes

2022-06-08 09:42 UTC, merged

2022-06-08 16:27 UTC, samholmes commented on src/common/utxobased/info/bitcoinsv.ts
> +    blockbookServers: ['ws://localhost:8008'],
Wrong initial push.