Add OP_RETURN to outputs
EdgeApp/edge-currency-plugins pull request #339
Opened 2022-07-20 23:47 UTC by GoodluckH

The added logics check if the `target` has memo, if so, we know it's 
an `OP_RETURN` script. Then, we use the altcoin.js lib to construct
an `OP_RETURN` script value.

However, if the memo (in hex string) exceeds the 80 bytes limitation
for `OP_RETURN` script, we throw.

2022-07-21 01:48 UTC, thehobbit85 requested changes

2022-07-21 01:48 UTC, thehobbit85 commented on src/common/utxobased/engine/utils.ts
> +export const getNumberOfBytesFromHex = (hex: string): number => {
This is very wasteful.
If you're string is already a valid hex sting, then the num of bytes is just `Math.ceil(hex.length / 2)`

2022-07-21 01:48 UTC, thehobbit85 commented on src/common/utxobased/engine/makeUtxoEngine.ts
> +              memo: target.memo == null ? undefined : target.memo
No need to check if it's null here, just add it directly.
You are testing for null anyway in the createTx function anyway.
About the type issue, see my next comment.

2022-07-21 01:48 UTC, thehobbit85 commented on src/common/utxobased/keymanager/keymanager.ts
> +  memo?: string
Change this type to `memo?: string | null` to fix the type issues you have

2022-07-21 01:48 UTC, thehobbit85 commented on src/common/utxobased/keymanager/keymanager.ts
> +      }
This should be written as the 'validateMemo' function in the makeCurrencyTools following this typing - https://github.com/EdgeApp/edge-core-js/blob/afbdb5ece2964ea09c29fb28b816ad8d9e726b19/src/types/types.js#L670

2022-07-21 18:05 UTC, thehobbit85 commented on src/common/utxobased/keymanager/keymanager.ts
> +      }
This is still not resolved, you should put the function on the currencyTools object.

2022-07-26 22:12 UTC, GoodluckH commented on src/common/utxobased/keymanager/keymanager.ts
> +  memo?: string | null
Address and value should also be optional.

2022-07-26 22:14 UTC, GoodluckH commented on src/common/utxobased/keymanager/keymanager.ts
> +
OpReturn should be an additional target with value of zero

2022-07-27 17:54 UTC, thehobbit85 commented
/rebase-autosquash

2022-07-27 17:58 UTC, thehobbit85 approved these changes

2022-07-27 17:58 UTC, merged