Refactor Engine State
EdgeApp/edge-currency-plugins pull request #73
Opened 2021-02-27 19:26 UTC by passabilities

### Merge Code Paths
The engine state has been refactored which simplifies the flow of into smaller modular functions. By doing this, the code paths that are executed when processing and address for the first time and while an address is subscribed to for new transactions is the same.

2021-03-04 00:09 UTC, passabilities commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +    perPage: 10,
set variable in constants file

2021-03-04 00:09 UTC, passabilities commented on src/common/utxobased/engine/makeUtxoEngineState.ts
>      processAddressBalance(args),
process balance in the utxo function

2021-03-06 06:13 UTC, thehobbit85 requested changes
Requested changes

2021-03-11 08:57 UTC, TheCharlatan commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> -  async function onNewBlock(): Promise<void> {
How is this handled now?

2021-03-15 17:48 UTC, thehobbit85 approved these changes

2021-03-15 17:49 UTC, merged