Get Transactions Fix
EdgeApp/edge-currency-plugins pull request #75
Opened 2021-03-01 21:49 UTC by passabilities

### Correctly Fetching Transaction Data
The function `fetchTransactions` did not properly fetch data from the database. If no params from the function arguments match, return all transaction in the db. Also because an `EdgeTransaction` has a parameter `ourReceiveAddresses` I remap the values stored in the db for `ourOuts` to get the `scriptPubkey` from the db and convert it to the addresses expected.

2021-03-03 15:24 UTC, thehobbit85 requested changes
Just needs to remove the misplaced code but other then that it looks good.

2021-03-03 15:24 UTC, thehobbit85 commented on src/common/utxobased/engine/makeUtxoEngineState.ts
> +
This doesn't belong in this PR.

2021-03-03 15:56 UTC, thehobbit85 approved these changes

2021-03-16 20:59 UTC, passabilities commented on src/common/utxobased/db/makeProcessor.ts
> +        startDate,
default `new Date(0)`

2021-03-16 20:59 UTC, passabilities commented on src/common/utxobased/db/makeProcessor.ts
> +        endDate
default `new Date()`

2021-03-16 20:59 UTC, passabilities commented on src/common/utxobased/db/makeProcessor.ts
> +      if (startEntries && startIndex) {
check if each is `null`

2021-03-16 21:12 UTC, thehobbit85 approved these changes

2021-03-16 21:12 UTC, merged