Engine Fees
EdgeApp/edge-currency-plugins pull request #79
Opened 2021-03-10 20:18 UTC by passabilities

### Fee Structure
Each currency info object has default fee values to use. Edge has their own server that returns some standard fee values for currencies that overwrite the defaults. Vendors, such as Earn.com and Mempool.space, are used to get more accurate up-to-date fee values on an interval that overwrites Edge's and the default values. 

These values are fetched and then cached to disk. On the next load, the engine fetches the cached values to then overwrite the currency defaults before it attempts to fetch fee values from Edge or any vendors.

### Calculate Rate
The previously implemented function, `calculateFeeRate`, has been replaced with the most recent implementation from [edge-bitcoin-plugin](https://github.com/EdgeApp/edge-currency-bitcoin/blob/d522ed1428/src/engine/miningFees.js#L195).

2021-03-30 03:15 UTC, passabilities reviewed
- separate vendor fetching from calculating.
- put calculating functionality in own file
- import test files from old bitcoin plugin

2021-03-30 03:15 UTC, passabilities commented on src/common/fees.ts
> +      const vendorFees = await fetchFeesFromVendor({
fetch fees from edge,
fetch fees from vendors - if ANY of them return then continue

2021-03-30 03:17 UTC, passabilities commented
build on top of changes made during PR review

2021-03-30 04:43 UTC, thehobbit85 requested changes
Address Comments and rebase/resolve conflicts

2021-04-03 04:10 UTC, thehobbit85 approved these changes

2021-04-03 04:11 UTC, merged