Make Metatdata
EdgeApp/edge-currency-plugins pull request #96
Opened 2021-03-29 02:59 UTC by passabilities

It creates a metadata object that listens to events from the engine and updates the wallet balance.
It listens for an event when an address balance changes and mutexes updating the wallet balance.
It reduces code duplication when sweeping a private key for the emitter.

2021-03-30 04:37 UTC, paullinator commented on src/common/plugin/makeMetadata.ts
> +    const dataStr = await disklet.getText(metadataPath)
Why? No need for memlet

2021-03-30 04:37 UTC, thehobbit85 requested changes
Address Comments and rebase/resolve

2021-03-30 04:39 UTC, thehobbit85 commented on src/common/plugin/makeMetadata.ts
> +    const dataStr = await disklet.getText(metadataPath)
Since you don't want to await on read/write to disk every time you update the balance/height

2021-04-02 23:25 UTC, thehobbit85 approved these changes

2021-04-02 23:25 UTC, merged